package com.proyecto.POJOS;
// Generated 10-oct-2018 15:45:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cuidadosplanta generated by hbm2java
 */
@Entity
@Table(name="cuidadosplanta"
    ,schema="public"
)
public class Cuidadosplanta  implements java.io.Serializable {


     private int id;
     private Planta planta;
     private String descripcion;

    public Cuidadosplanta() {
    }

	
    public Cuidadosplanta(int id) {
        this.id = id;
    }
    public Cuidadosplanta(int id, Planta planta, String descripcion) {
       this.id = id;
       this.planta = planta;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_planta")
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }

    
    @Column(name="descripcion", length=5000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


