package com.proyecto.POJOS;
// Generated 10-sep-2018 14:00:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cultivo generated by hbm2java
 */
@Entity
@Table(name="cultivo"
    ,schema="public"
)
public class Cultivo  implements java.io.Serializable {


     private int id;
     private Huerto huerto;
     private Planta planta;
     private String progreso; 
     private Date fechaSiembra;
     private Date fechaInicialCosecha;
     private Date fechaFinalCosecha;

    public Cultivo() {
    }

    public Cultivo(int id, Huerto huerto, Planta planta, Date fechaSiembra) {
       this.id = id;
       this.huerto = huerto;
       this.planta = planta;
       this.fechaSiembra = fechaSiembra;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_huerto", nullable=false)
    public Huerto getHuerto() {
        return this.huerto;
    }
    
    public void setHuerto(Huerto huerto) {
        this.huerto = huerto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_planta", nullable=false)
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_siembra", nullable=false, length=13)
    public Date getFechaSiembra(){
        
        return this.fechaSiembra;
    }
    
    public void setFechaSiembra(Date fechaSiembra) {
        this.fechaSiembra = fechaSiembra;
    }

    public String getProgreso() {
        return progreso;
    }

    public void setProgreso(String progreso) {
        this.progreso = progreso;
    }

    public Date getFechaInicialCosecha() {
        return fechaInicialCosecha;
    }

    public void setFechaInicialCosecha(Date fechaInicialCosecha) {
        this.fechaInicialCosecha = fechaInicialCosecha;
    }

    public Date getFechaFinalCosecha() {
        return fechaFinalCosecha;
    }

    public void setFechaFinalCosecha(Date fechaFinalCosecha) {
        this.fechaFinalCosecha = fechaFinalCosecha;
    }
    
    
}


