package com.proyecto.POJOS;
// Generated 10-oct-2018 15:45:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Historialrecomendacion generated by hbm2java
 */
@Entity
@Table(name="historialrecomendacion"
    ,schema="public"
)
public class Historialrecomendacion  implements java.io.Serializable {


     private int id;
     private Recomendacion recomendacion;
     private Usuario usuario;

    public Historialrecomendacion() {
    }

	
    public Historialrecomendacion(int id) {
        this.id = id;
    }
    public Historialrecomendacion(int id, Recomendacion recomendacion, Usuario usuario) {
       this.id = id;
       this.recomendacion = recomendacion;
       this.usuario = usuario;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_recomendacion")
    public Recomendacion getRecomendacion() {
        return this.recomendacion;
    }
    
    public void setRecomendacion(Recomendacion recomendacion) {
        this.recomendacion = recomendacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}


