package com.proyecto.POJOS;
// Generated 10-sep-2018 14:00:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Huerto generated by hbm2java
 */
@Entity
@Table(name="huerto"
    ,schema="public"
)
public class Huerto  implements java.io.Serializable {


     private int id, numeroCultivo;
     private Usuario usuario;
     private String nombre;
     private String rutaimagen;
     private String descripcion;
     private String area;
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);

    public Huerto() {
    }

	
    public Huerto(int id, Usuario usuario, String nombre) {
        this.id = id;
        this.usuario = usuario;
        this.nombre = nombre;
    }
    public Huerto(int id, Usuario usuario, String nombre, String rutaimagen, String descripcion, String area, Set<Cultivo> cultivos) {
       this.id = id;
       this.usuario = usuario;
       this.nombre = nombre;
       this.rutaimagen = rutaimagen;
       this.descripcion = descripcion;
       this.area = area;
       this.cultivos = cultivos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", nullable=false, length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="rutaimagen", length=150)
    public String getRutaimagen() {
        return this.rutaimagen;
    }
    
    public void setRutaimagen(String rutaimagen) {
        this.rutaimagen = rutaimagen;
    }

    
    @Column(name="descripcion", length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="area")
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="huerto")
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }

    public int getNumeroCultivo() {
        return numeroCultivo;
    }

    public void setNumeroCultivo(int numeroCultivo) {
        this.numeroCultivo = numeroCultivo;
    }

    


}


