package com.proyecto.POJOS;
// Generated 10-sep-2018 14:00:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Planta generated by hbm2java
 */
@Entity
@Table(name="planta"
    ,schema="public"
)
public class Planta  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String rutaimagen;
     private String especie;
     private String caracteristicas;
     private String tamano;
     private String periodoSiembra;
     private String aprovechamiento;
     private Integer diasACosechar;
     private Set<Cultivo> cultivos = new HashSet<Cultivo>(0);

    public Planta() {
    }

	
    public Planta(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Planta(int id, String nombre, String rutaimagen, String especie, String caracteristicas, String tamano, String periodoSiembra, String aprovechamiento, Integer diasACosechar, Set<Cultivo> cultivos) {
       this.id = id;
       this.nombre = nombre;
       this.rutaimagen = rutaimagen;
       this.especie = especie;
       this.caracteristicas = caracteristicas;
       this.tamano = tamano;
       this.periodoSiembra = periodoSiembra;
       this.aprovechamiento = aprovechamiento;
       this.diasACosechar = diasACosechar;
       this.cultivos = cultivos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="rutaimagen", length=150)
    public String getRutaimagen() {
        return this.rutaimagen;
    }
    
    public void setRutaimagen(String rutaimagen) {
        this.rutaimagen = rutaimagen;
    }

    
    @Column(name="especie", length=25)
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }

    
    @Column(name="caracteristicas", length=3000)
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }

    
    @Column(name="tamano", length=25)
    public String getTamano() {
        return this.tamano;
    }
    
    public void setTamano(String tamano) {
        this.tamano = tamano;
    }

    
    @Column(name="periodo_siembra", length=250)
    public String getPeriodoSiembra() {
        return this.periodoSiembra;
    }
    
    public void setPeriodoSiembra(String periodoSiembra) {
        this.periodoSiembra = periodoSiembra;
    }

    
    @Column(name="aprovechamiento", length=25)
    public String getAprovechamiento() {
        return this.aprovechamiento;
    }
    
    public void setAprovechamiento(String aprovechamiento) {
        this.aprovechamiento = aprovechamiento;
    }

    
    @Column(name="dias_a_cosechar")
    public Integer getDiasACosechar() {
        return this.diasACosechar;
    }
    
    public void setDiasACosechar(Integer diasACosechar) {
        this.diasACosechar = diasACosechar;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="planta")
    public Set<Cultivo> getCultivos() {
        return this.cultivos;
    }
    
    public void setCultivos(Set<Cultivo> cultivos) {
        this.cultivos = cultivos;
    }




}


