package com.proyecto.POJOS;
// Generated 10-sep-2018 14:00:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,schema="public"
)
public class Producto  implements java.io.Serializable {


     private int id;
     private Vivero vivero;
     private String nombre;
     private String descripcion;
     private String marca;
     private String tipo;

    public Producto() {
    }

	
    public Producto(int id, Vivero vivero, String nombre) {
        this.id = id;
        this.vivero = vivero;
        this.nombre = nombre;
    }
    public Producto(int id, Vivero vivero, String nombre, String descripcion, String marca, String tipo) {
       this.id = id;
       this.vivero = vivero;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.marca = marca;
       this.tipo = tipo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vivero", nullable=false)
    public Vivero getVivero() {
        return this.vivero;
    }
    
    public void setVivero(Vivero vivero) {
        this.vivero = vivero;
    }

    
    @Column(name="nombre", nullable=false, length=15)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="marca", length=15)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="tipo", length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


