package com.proyecto.POJOS;
// Generated 10-oct-2018 15:45:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recomendacion generated by hbm2java
 */
@Entity
@Table(name="recomendacion"
    ,schema="public"
)
public class Recomendacion  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Date fecha;
     private String tipo;
     private String rutaimagen;


    public Recomendacion() {
    }

	
    public Recomendacion(int id) {
        this.id = id;
    }
    public Recomendacion(int id, String nombre, String descripcion, Date fecha, String tipo, String rutaimagen){
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.tipo = tipo;
       this.rutaimagen = rutaimagen;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=3000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="tipo", length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="rutaimagen", length=3000)
    public String getRutaimagen() {
        return this.rutaimagen;
    }
    
    public void setRutaimagen(String rutaimagen) {
        this.rutaimagen = rutaimagen;
    }


}


