package com.proyecto.POJOS;
// Generated 10-sep-2018 14:00:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vivero generated by hbm2java
 */
@Entity
@Table(name="vivero"
    ,schema="public"
)
public class Vivero  implements java.io.Serializable {


     private int idVivero;
     private String nombrevivero;
     private String direccion;
     private String cuidad;
     private String correo;
     private String contrasena;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Vivero() {
    }

	
    public Vivero(int idVivero, String nombrevivero, String correo, String contrasena) {
        this.idVivero = idVivero;
        this.nombrevivero = nombrevivero;
        this.correo = correo;
        this.contrasena = contrasena;
    }
    public Vivero(int idVivero, String nombrevivero, String direccion, String cuidad, String correo, String contrasena, Set<Producto> productos) {
       this.idVivero = idVivero;
       this.nombrevivero = nombrevivero;
       this.direccion = direccion;
       this.cuidad = cuidad;
       this.correo = correo;
       this.contrasena = contrasena;
       this.productos = productos;
    }
   
     @Id 

    
    @Column(name="id_vivero", unique=true, nullable=false)
    public int getIdVivero() {
        return this.idVivero;
    }
    
    public void setIdVivero(int idVivero) {
        this.idVivero = idVivero;
    }

    
    @Column(name="nombrevivero", nullable=false, length=15)
    public String getNombrevivero() {
        return this.nombrevivero;
    }
    
    public void setNombrevivero(String nombrevivero) {
        this.nombrevivero = nombrevivero;
    }

    
    @Column(name="direccion", length=25)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="cuidad", length=15)
    public String getCuidad() {
        return this.cuidad;
    }
    
    public void setCuidad(String cuidad) {
        this.cuidad = cuidad;
    }

    
    @Column(name="correo", nullable=false, length=25)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contrasena", nullable=false, length=25)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vivero")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


